name: studentapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_circular_chart: ^0.0.3
  banner_view: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/launcher.jpg
    - images/bar_icon_reading_circle.png
    - images/bar_icon_reading_circle2.png
    - images/img_tab_guide.png
    - images/img_tab_guide_normal.png
    - images/img_tab_library.png
    - images/img_tab_library_normal.png
    - images/img_tab_userinfo.png
    - images/img_tab_userinfo_normal.png
    - images/home_bg.png
    - images/home_icon_habit.png
    - images/defaul_head_parent.png
    - images/homepage_bg_top.png
    - images/homepage_icon_pass.png
    - images/homepage_icon_today.png
    - images/homepage_bg_list.png
    - images/homepage_btn_arrow_L.png
    - images/homepage_btn_arrow_ese.png
    - images/homepage_banner_ad1.png
    - images/homepage_banner_ad2.png
    - images/homepage_banner_ad3.png
    - images/icon_Lv1.png
    - images/icon_Lv2.png
    - images/icon_Lv3.png
    - images/icon_Lv4.png
    - images/task_banner_ad1.png
    - images/task_banner_ad2.png
    - images/task_banner_ad3.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
